
package com.mycompany.loginu;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author osmar
 */
public class newUser extends javax.swing.JFrame {

    /**
     * Creates new form newUser
     */
    public newUser() { // this is the constructor 
        initComponents();
        setLocationRelativeTo(null);
        jcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Password:");

        jLabel4.setText("Role:");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Go back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        nwUser();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void nwUser(){
        
        if (jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jTextField3.getText().isEmpty()||jComboBox1.getSelectedItem()== null) {
                     JOptionPane.showMessageDialog(this, "We cannot process your request, some fields are still empty");
        }else{
            
        User u = new User();
        u.setUser(jTextField1.getText());
        u.setName(jTextField2.getText());
        u.setPassword(jTextField3.getText());
        
        
        String rol = jComboBox1.getSelectedItem().toString();
        
        if(rol.equals("Manager")){
            u.setRole(1);
        }else{
            u.setRole(2);
        }
        
        boolean exist = false;
        
            
        if (jTextField3.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "You're password should contain more than 6 digits");
            return;
        }
        
        boolean pUppercase = false;
        boolean pLowercase = false;
        boolean pDigit = false;
        
        for(char c : u.getPassword().toCharArray()){
            if (Character.isUpperCase(c)) {
                pUppercase = true;
            }else if(Character.isLowerCase(c)){
                pLowercase = true;
            }else if(Character.isDigit(c)){
                pDigit = true;
            }
        }
        
        if (!pUppercase || !pLowercase || !pDigit ) {
            JOptionPane.showMessageDialog(this, "Password must contain at least\n one uppercase letter,\n one lowercase letter,\n one number.");
        return;
        }
        
            
        for(User a : LogU.users){
            if (a.getUser().equals(jTextField1.getText())) {
                JOptionPane.showMessageDialog(this, "That userID is already registered\nTry another one");
            exist = true;
            break; 
            }
        }
        
        
        if (!exist) {
            LogU.users.add(u);
            saveUser();
            JOptionPane.showMessageDialog(this, "Account successfully created");
        clean();
        }
        
        
        }
        
    }
    
    public void saveUser(){
        
        FileWriter folder = null;
                PrintWriter write = null;
            try {
                folder = new FileWriter("QueryCx.xml");
                write = new PrintWriter(folder);
                
                write.println("<users>");
                
                    for(User us: LogU.users){
                        
                        write.println("<user>");
                            write.println("<name>"+us.getName()+"</name>");
                            write.println("<usr>"+us.getUser()+"</usr>");
                            write.println("<password>"+us.getPassword()+"</password>");
                            write.println("<role>"+us.getRole()+"</role>");
                        
                        write.println("</user>");
                        
                    }
                write.println("</users>");
                
            } catch (IOException ex) {
                Logger.getLogger(newUser.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    folder.close();
                } catch (IOException ex) {
                    Logger.getLogger(newUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }
    
   public void jcombo(){ 
       jComboBox1.removeAllItems();
       jComboBox1.addItem("Manager");
       jComboBox1.addItem("Seller");
       jComboBox1.setSelectedIndex(-1);
   }
    
    public void clean(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(-1);
       
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
